### ISSUE TITLE
Unyank the latest release

### ISSUE THREAD

**Issue by TheNeikos** [untitaker/iron-login#11]
Since you yanked the whole thing it breaks at least `cargo update` as it tries to update but doesn't find anything at all (due to them being all yanked). I see no reason to switch to another crate (yet). 

I don't think you did this on purpose, however it would help a lot if you could re-instate the last release.

**Comment by untitaker** [comment]
I don't maintain this crate anymore. I am not sure what to do in such situations, but yanking seemed like a way to get attention. I recommend https://github.com/untitaker/iron-sessionstorage instead.

**Comment by TheNeikos** [comment]
You should have used the `deprecated` attribute on the main structs and in combination of the readme it would still compile but give a warning everytime one tries to compile (which imo is more than enough)

**Comment by untitaker** [comment]
Unyanked everything and deprecated the struct necessary for any kind of usage.

**Comment by TheNeikos** [comment]
Awesome thanks!
