### ISSUE TITLE
Change `username` to `uuid`

### ISSUE THREAD

**Issue by KalitaAlexey** [untitaker/iron-login#2]
Currently `Login` and `User` work with `username`. But it is `uuid`.

**Comment by untitaker** [comment]
This doesn't make any sense. UUID has a special meaning: https://en.wikipedia.org/wiki/Universally_unique_identifier

The `username` may or may not be a UUID.

**Comment by KalitaAlexey** [comment]
User may not have any name. But it must have any unique ID to disambiguate several users.

**Comment by untitaker** [comment]
Under POSIX, usernames are unique IDs. Those are the usernames I'm talking
about.

For all I care it could be called `user_id`, but UUID is wrong.

**Comment by KalitaAlexey** [comment]
@untitaker I will change to `user_id`. Okay?

**Comment by untitaker** [comment]
I'd merge that, but I don't feel too strongly about it.

**Comment by KalitaAlexey** [comment]
@untitaker I mean `user name` is something what is called `name` in normal life.

**Comment by untitaker** [comment]
Probably. ¯_(ツ)_/¯
