### ISSUE TITLE
Impossible to implement User unless user_id is stored directly in the implementing struct

### ISSUE THREAD

**Issue by emosenkis** [untitaker/iron-login#5]
Since get_user_id() returns a &str instead of String, it is not possible to create that &str inside the function and return it since the lifetime will be incorrect.

**Comment by untitaker** [comment]
I always assumed that you'd store the string inside the user. When is this not the case?

**Comment by emosenkis** [comment]
In my case, I'm using a user_id string that encodes multiple pieces of data (a domain and an identifier), so I'd like to store those as two separate fields in memory even though I have to combine them to create a user_id string. The same issue would apply in any case when a string is not an ideal representation for a user.

**Comment by untitaker** [comment]
I see. I think it's sad that we have to copy around strings like this, but I don't think we have a choice.

**Comment by untitaker** [comment]
There might be a way to generalize the trait in a way such that you can just return a tuple, or any other type that uniquely identifies your user.

**Comment by untitaker** [comment]
@emosenkis Does #6 work for you? It doesn't currently work for mine, but I think if you don't use slices/references/pointers for defining `User::Id`, you'll be fine.

**Comment by untitaker** [comment]
I just found that the approach doesn't work very well, I'll try around a bit more, but it seems like we'll have to require returning `String` instead.

**Comment by untitaker** [comment]
Nvm all this nonsense, we're not saving anything because when creating the cookie, we need to create a `String` anyway.

**Comment by untitaker** [comment]
Version 0.3.0 is out.
